
<h1><?php echo $this->title;?></h1>

<?php

$form = $this->form;
$form->prepare();

$form->setAttributes(array(
    //"action" => $this->basePath()."/get-form",
    "action" => "",
    "method" => "post"
));

$formLabel = $this->plugin("formLabel");
echo $this->form()->openTag($form); 

echo $this->formCollection($form); 
 
echo $this->form()->closeTag();
?>

<div class="form_element">
<?php
/*En estas lineas de codigo seria cuando no hacemos el llamado en general del formulario
lineas arriba */
// $activo=$form->get('activo');
// echo "Activo:".$this->formSelect($activo);
?>
</div>

